import React, { useEffect, useRef } from 'react';
import clsx from 'clsx';
import Layout from '@theme/Layout';
import DocSidebar from '@theme/DocSidebar';
import { ThemeClassNames } from '@docusaurus/theme-common';
import styles from './styles.module.css';
import { PropSidebarItem } from '@docusaurus/plugin-content-docs';
import {useLocation} from '@docusaurus/router';
import { useColorMode } from '@docusaurus/theme-common';

import items from './sidebar.cjs'; // generated by storybook plugin

// Get the query containing the id of the doc we want to display
function useQuery() {
  const { search } = useLocation();

  return React.useMemo(() => new URLSearchParams(search), [search]);
}

// the iframe is by default not taking all height
// adding an observer to ensure it always takes all the space it need
function observe( iframe ) {
  const body = iframe.contentDocument.body;

  const observerCallback: ResizeObserverCallback = (entries: ResizeObserverEntry[]) => {
    window.requestAnimationFrame((): void | undefined => {
      if (!Array.isArray(entries) || !entries.length) {
        return;
      }
      iframe.style.height = `${body.scrollHeight}px`;
    });
  };
  const resizeObserver = new ResizeObserver(observerCallback);
  resizeObserver.observe(body);
}

function StorybookRoot() {
  let query = useQuery();
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const { isDarkTheme } = useColorMode();
  const id = query.get('id');

  useEffect(() => {
    // we send the iframe the dark mode change https://storybook.js.org/addons/storybook-dark-mode
    iframeRef.current.contentWindow.postMessage(JSON.stringify({
      "key":"storybook-channel",
      "event":{"type":"DARK_MODE","args":[isDarkTheme]}
    }));
  }, [isDarkTheme]);

  const storybookItems: PropSidebarItem[] = items.map((item) => ({
    type: 'link',
    href: `/storybook?id=${item.id}`,
    label: item.label
  }));

  return (
      <div className={clsx(styles.storybookRoot)}>
        <aside className={clsx(
          ThemeClassNames.docs.docSidebarContainer,
          styles.docSidebarContainer
        )}>
          <DocSidebar isHidden={false} onCollapse={() => {}} sidebar={storybookItems} path="/storybook">
          </DocSidebar>
        </aside>
        <iframe ref={iframeRef} onLoad={e => observe(e.target)} src={`/storybook-iframe?id=${id}`} style={{ width: '100%', height: '100%'}}/>
      </div>
  );
}

// to use `useColorMode` we need to be wrapped in Layout component
// ref https://docusaurus.io/docs/api/themes/configuration#use-color-mode
export default function Storybook() {
 return (
   <Layout title="Storybook">
     <StorybookRoot/>
   </Layout>
 )
}
