name: Bug 🐞
description: Report a bug report
labels: [kind/bug 🐞]

body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues.

        ---

        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What happened?
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      description: "Which operating system are you on? Please provide the version as well. If you are on a Mac, please specify Apple silicon or Intel."
      placeholder: "macOS Ventura 13.4 (Arm), Windows 11"
    validations:
      required: true

  - type: dropdown
    id: install
    attributes:
      label: Installation Method
      description: "How did you install Podman Desktop ?"
      options:
        - "Installer from website/GitHub releases"
        - "Brew (macOS)"
        - "Chocolatey (Windows)"
        - "Flathub (Linux)"
        - "Scoop (Windows)"
        - "Winget (Windows)"
        - "Other"

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      options:
        - "1.11.1"
        - "1.12.0"
        - "next (development version)"
        - "1.11.0"
        - "1.10.2"
        - "1.10.1"
        - "1.10.0"
        - "1.9.x"
        - "1.8.x"
        - "1.7.x"
        - "1.6.x"
        - "1.5.x"
        - "1.4.x"
        - "1.3.x"
        - "1.2.x"
        - "1.1.x"
        - "1.0.x"
        - "0.x"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: What steps do we need to take to reproduce this error?

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output.
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots here.
