#!/bin/sh
# This script is generated by Podman Desktop
    
# Add into the PATH the folder where docker-compose is installed
export PATH="$PATH:{{{ binFolder }}}"
    
# Set the DOCKER_HOST to the socket of the podman service
export DOCKER_HOST=unix://{{{ socketPath }}}
    
docker-compose "$@"
