---
title: Onboarding for Kubernetes workloads
config:
    theme: "base"
    themeVariables:
        darkmode: true
        background: "#000000"
        fontFamily: "Montserrat"
        fontSize: 16px
        primaryBorderColor: "#8b5cf6"
        primaryColor: "#8b5cf6"
        primaryTextColor: "#cccccc"
        secondaryBorderColor: "#8f81d3"
        secondaryColor: "#8f81d3"
        tertiaryBorderColor: "#d721ff"
        tertiaryColor: "#d721ff"
        noteBorderColor: "#fff5ad"
        noteBkgColor: "#fff5ad"
---

mindmap
  root((Kubernetes))
    Select context based on your Kube config
    Kind
    Minikube
    Lima
    Red Hat OpenShift Local
    Red Hat Developer Sandbox
