---
title: Onboarding for Kubernetes workloads
config:
    theme: "base"
    themeVariables:
        darkmode: true
        background: "#000000"
        fontFamily: "Montserrat"
        fontSize: 16px
        primaryBorderColor: "#8b5cf6"
        primaryColor: "#8b5cf6"
        primaryTextColor: "#cccccc"
        secondaryBorderColor: "#8f81d3"
        secondaryColor: "#8f81d3"
        tertiaryBorderColor: "#d721ff"
        tertiaryColor: "#d721ff"
        noteBorderColor: "#fff5ad"
        noteBkgColor: "#fff5ad"
---

mindmap
  root))Onboarding for Kubernetes in Podman Destktop((
    Select context based on your Kube config
    Setup Container engine
        Setup Kind
        Setup Minikube
    Select Lima
        k3s
        k8s
    Setup Red Hat OpenShift Local
        MicroShift
        OpenShift
    Setup access to Red Hat Developer Sandbox
